version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: lexicom-tt
    container_name: lexicom-tt
    restart: always
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
